server:
  port: 8088
  servlet:
    context-path: /course

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-b6fcgmw2.cd.tencentcdb.com:10053/TOFEL?serverTimezone=Asia/Shanghai
    username: groupsix
    password: chinasoft6
    hikari:
      max-lifetime: 30000
  application:
    name: course
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml
feign:
  httpclient:
    enabled: true
